[[manager.prepend_keymap]]
on = "M"
run = "plugin mount"
desc = "mount drives"

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "chmod on selected files"

[[manager.keymap]]
on = "u"
run = "plugin restore"
desc = "Restore last deleted files/folders"
