[manager]
ratio = [2, 4, 3]

[opener]
extract = [
    { run = 'ouch d -y "%*"', desc = "Extract with ouch", for = "windows" },
    { run = 'ouch d -y "$@"', desc = "ExtractO with ouch", for = "unix" },
]

[plugin]
prepend_previewers = [
    { name = "*.md", run = "glow" },
    # Archive previewer
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
    { mime = "application/xz", run = "ouch" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
